/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dbd9d9",
        "on-tertiary-fixed": "#151c22",
        "on-surface-variant": "#43474f",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#a9c7ff",
        "on-secondary-fixed": "#001b3d",
        "tertiary-fixed": "#dce3eb",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed-variant": "#00468c",
        "primary-container": "#003366",
        "tertiary-container": "#2d343a",
        tertiary: "#181f25",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#efeded",
        "surface-container-highest": "#e4e2e2",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d5e3ff",
        "surface-bright": "#fbf9f8",
        "on-tertiary-container": "#959ca4",
        "inverse-on-surface": "#f2f0f0",
        "surface-container-high": "#eae8e7",
        "on-tertiary-fixed-variant": "#40484e",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        primary: "#001e40",
        "surface-tint": "#3a5f94",
        "surface-container-low": "#f5f3f3",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-primary-container": "#799dd6",
        secondary: "#005db6",
        "inverse-surface": "#303030",
        "on-surface": "#1b1c1c",
        "on-secondary-container": "#00376f",
        background: "#fbf9f8",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-background": "#1b1c1c",
        "surface-variant": "#e4e2e2",
        "on-error": "#ffffff",
        surface: "#fbf9f8",
        "secondary-fixed": "#d6e3ff",
        "secondary-container": "#63a1ff",
        "on-primary-fixed-variant": "#1f477b",
        "inverse-primary": "#a7c8ff",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c6d1",
        outline: "#737780",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xl: "64px",
        gutter: "24px",
        xs: "8px",
        sm: "16px",
        lg: "40px",
        base: "4px",
        md: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-md": ["Public Sans", "sans-serif"],
        "headline-sm": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "display-lg-mobile": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
