/**
 * Converts the React form state (camelCase) into the exact shape expected
 * by the backend `EleveRequest` DTO (snake_case / payId).
 */
export function toEleveRequest(form) {
  return {
    nom: form.nom.trim(),
    prenom: form.prenom.trim(),
    nom_ar: form.nomAr?.trim() || null,
    sexe: form.sexe,
    date_naissance: form.dateNaissance,
    lieu_naissance: form.lieuNaissance?.trim() || null,
    payId: form.payId ? Number(form.payId) : null,
    adresse: form.adresse?.trim() || null,
    cin: form.cin?.trim() || null,
    nom_pere: form.nomPere?.trim() || null,
    profession_pere: form.professionPere?.trim() || null,
    mobile: form.mobile?.trim() || null,
    fixe: form.fixe?.trim() || null,
    email: form.email.trim(),
    identifiant_unique: form.identifiantUnique?.trim() || null,
    prenom_ar: form.prenomAr?.trim() || null,
    password: form.password,
    photo: null,
    profile: form.profile,
    lu_condition: Boolean(form.luCondition),
    militaire: Boolean(form.militaire),
    reclassement: Boolean(form.reclassement),
    tarif: form.tarif || null,
    parent_culture: form.parentCulture?.trim() || null,
    drpp_parent: form.drppParent?.trim() || null,
    lien_parente: form.lienParente || null,
    frais_imprime: Boolean(form.fraisImprime),
  };
}

export const INITIAL_REGISTRATION_FORM = {
  nom: '',
  prenom: '',
  nomAr: '',
  prenomAr: '',
  sexe: '',
  dateNaissance: '',
  lieuNaissance: '',
  payId: '',
  adresse: '',
  cin: '',
  nomPere: '',
  professionPere: '',
  mobile: '',
  fixe: '',
  email: '',
  identifiantUnique: '',
  password: '',
  confirmPassword: '',
  profile: '',
  militaire: false,
  reclassement: false,
  tarif: '',
  parentCulture: '',
  drppParent: '',
  lienParente: '',
  fraisImprime: false,
  luCondition: false,
};
